### ISSUE TITLE
return type for batch() is wrong on typescript

### ISSUE THREAD

**Issue by juicycool92** [mariadb-corporation/mariadb-connector-nodejs#194] opened 2022-03-15 03:57 UTC
mariadb version : `3.0.0`
operating os : `ubuntu 20.04`

Hello, 
thanks for nice module!

i have a question about types for `batch()` function

please, see the look at my code screenshot first.

![image](https://user-images.githubusercontent.com/12273678/158302622-1846470a-d048-4a8f-9251-2bc1eff67552.png)

above code are working perfectly, and i want to look how many of rows are affected like this variable from [this docs](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/master/documentation/promise-api.md#connectionbatchsql-values--promise)

but there is types error on my IDE
![image](https://user-images.githubusercontent.com/12273678/158302999-06cff45c-6465-4c9f-a000-92cbc0bb91ca.png)

i checked d.ts file and this look like array
![image](https://user-images.githubusercontent.com/12273678/158303089-2461a5ba-e565-40c6-8045-52b17c890460.png)

after that, i tried to log the result and what exactly result look like.
`[2022-03-15T03:18:41+00:00][logger][error]: {"affectedRows":1,"insertId":"0","warningStatus":0}`

so, it looks like there is type declare error or i might be doin wrong totally.
can you help me what did i do wrong?

Thanks!

**Comment by antoHuman** [comment] 2022-05-26 11:09
I can confirm the same issue with the return type. The promise resolves with the `UpsertResult` object (e. g. `{"affectedRows":2,"insertId":"10","warningStatus":0}`), when inserting multiple values, not with an array of those.

Are there some cases for which it actually returns `UpsertResult[]`?

I guess we need to use `// @ts-ignore` for now, or override the interface?

mariadb version : `2.5.5`
operating os : Windows 10

**Comment by rusher** [comment] 2023-02-02 09:52
closing since corrected with [CONJS-199](https://jira.mariadb.org/browse/CONJS-199) on 2.5.7/3.0.1

**Closed by rusher** 2023-02-02 09:52 UTC
