### ISSUE TITLE
Failed to create socket error

### ISSUE THREAD

**Issue by gunsela92** [mariadb-corporation/mariadb-connector-nodejs#224] opened 2022-11-30 13:09 UTC
Im using sequelize. Sometimes im getting this error i dont know why. How can i increase the timeout ?

```
    text: 'Connection timeout: failed to create socket after 1010ms',
    sql: null,
    fatal: true,
    errno: 45012,
    sqlState: '08S01',
    code: 'ER_CONNECTION_TIMEOUT'
```

My code ;

```
  const { host, port, user, password, database, poolMax, poolMin, dialect, acquire, idle } = config.database;
  const connection = await mariadb.createConnection({
    host: host,
    port: port,
    user: user,
    password: password,
    database: database,
    multipleStatements: true,
  });
  await connection.query(`CREATE DATABASE IF NOT EXISTS \`${database}\`;`);

  // connect to db
  const sequelize = new Sequelize(database, user, password, {
    host: host,
    port: port,
    dialect: dialect,
    operatorsAliases: false,
    timeout: 10000,
    dialectOptions: {
      options: {
        requestTimeout: 60000,
        connectTimeout: 60000
      }
    },
    pool: {
      max: poolMax,
      min: poolMin,
      acquire: acquire,
      idle: idle,
    }
  });
```

**Comment by rusher** [comment] 2023-01-10 17:32
closing issue, since this is not a bug, but documentation link request

**Closed by rusher** 2023-01-10 17:32 UTC
