### ISSUE TITLE
Batch inserts Dates < 1970-01-01 00:00:01 as nulls

### ISSUE THREAD

**Issue by urugator** [mariadb-corporation/mariadb-connector-nodejs#287] opened 2024-05-27 09:52 UTC
[Batch seems to treat all `Date` objects as `TIMESTAMP`](https://github.com/mariadb-corporation/mariadb-connector-nodejs/blob/d0913b46e1209016d4b6cad6841057d9cc656445/lib/cmd/batch-bulk.js#L102C40-L102C58) even though the actual column is `DATETIME`/`DATE`. The TIMESTAMP values are restricted to `1970-01-01 00:00:01` - `2038-01-19 03:14:07`/`2106-02-07 06:28:15`, so if a date represented by the Date object is outside of this range, it's treated as `null`. If we attempt to insert the same date using string instead of Date object, everything works as expected.

**Comment by rusher** [comment] 2024-05-27 09:58
right, this is indeed an error, on first glance it must be a FieldType.DATETIME in place of FieldType.TIMESTAMP. 
I need to test that first with value range to confirm.

**Comment by rusher** [comment] 2024-05-27 10:01
strange i don't reproduce this problem. What type of server+version are you using ?

**Comment by urugator** [comment] 2024-05-27 10:12
Client: `3.3.0`
Server:`10.6.7-MariaDB`

**Comment by rusher** [comment] 2024-05-27 12:05
allright, reproduced

**Comment by rusher** [comment] 2024-07-05 09:23
closing, since released in 3.3.1

**Closed by rusher** 2024-07-05 09:23 UTC
