### ISSUE TITLE
acquireTimeout not working for idleConnections > 0

### ISSUE THREAD

**Issue by lschmierer** [mariadb-corporation/mariadb-connector-nodejs#116] opened 2020-06-16 16:03 UTC
When idle connections are present while the database connection gets lost, `pool.getConnection()` does not resolve with an error after `acquireTimeout`.

The reason seems to be that the pool tries to ping the server.
With default `socketTimeout: 0`, this runs indefinitely.

I looked into writing an integration test, but was not sure how to simulate "external connection loss".

## Reproduce
1. Create `Pool`.
2. Shutdown database.
3. Call `pool.getConnection()`
=> does not time out.

**Comment by rusher** [comment] 2020-06-30 19:35
allright, found and reproduced the issue. 
Do you use some proxy between client and server ? Socket usually not stay very long in this kind of waiting state normally, but if there is some proxy. 

Correction will be done quickly.

**Comment by lschmierer** [comment] 2020-06-30 21:35
Ah yes, makes sense.

I used xampp-vm for macOS, which runs the database in a local virtual machine.
It might virtualization that keeps the socket waiting longer than normally.

Thanks for the fix!

**Comment by rusher** [comment] 2020-08-18 13:36
closing since released in 2.4.2

**Closed by rusher** 2020-08-18 13:36 UTC
