### ISSUE TITLE
Got a packet bigger than 'max_allowed_packet' bytes

### ISSUE THREAD

**Issue by Orel-A** [mariadb-corporation/mariadb-connector-nodejs#297] opened 2024-10-21 16:13 UTC
I'm having a problem with this library which I didn't have before.
On a production server, Windows Server 2022 on the logs I have 2 logs:
```
Application has thrown an uncaught exception and is terminated:
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:218:20)
```
The second one:
```
Application has thrown an uncaught exception and is terminated:
SqlError: (conn:908, no: 1153, SQLState: 08S01) Got a packet bigger than 'max_allowed_packet' bytes
sql: INSERT INTO country_ips (startAddress, endAddress, country) VALUES (INET6_ATON(?), INET6_ATON(?), ?) - parameters:[['2001:200::','2001:200:ffff:ffff:ffff:ffff:ffff:ffff','JP'],['2001:208::','2001:208:ffff:ffff:ffff:ffff:ffff:ffff','SG'],['2001:218::','2001...
```

On the development PC I only get the ECONNRESET error.
How can I resolve this issue?

I suspect it's related to this issue: https://github.com/mariadb-corporation/mariadb-connector-nodejs/issues/281

EDIT: I found a temporary solution. I set maxAllowedPacket to 4MB on createPool.
But take note: my `max_allowed_packet` is set to 16777216 which is 16MB exactly.
So the library knows the correct limit of my MariaDB server and shouldn't crash. However it does.
So something else is at play. Maybe the calculation has a problem. An overhead of some sort that isn't calculated?

**Comment by rusher** [comment] 2024-10-21 16:54
Strange, because the default behavior of batch is limiting packet to 16Mb maximum by default, i'll have to reproduce that

**Comment by rusher** [comment] 2024-10-23 10:17
received. Thanks, i'll look at that

**Comment by Orel-A** [comment] 2024-10-26 19:24
I'm wondering if you were able to reproduce the error?

**Comment by rusher** [comment] 2024-10-28 10:08
not for now, could you indicate some additional details: server version, cnf file ? and connector version ? 
i've tryed with latest connector version on windows 11 and different mariadb server set to max-allowed-packet=16M without problem.

**Comment by Orel-A** [comment] 2024-10-28 12:59
Yeah, I also don't get the error anymore, but I know why.
The ZIP file on the server has been updated to a new version and with this version the error doesn't occur.

I've sent you the old ZIP file that causes the bug to your email.

**Comment by rusher** [comment] 2024-10-28 13:17
ok, thanks, issue reproduced with the old file. I'll digg into it now

**Comment by rusher** [comment] 2024-10-28 16:26
Thanks for the clear repeatable case @Orel-A ! 
This is corrected in develop branch, and will be part of next release

**Closed by rusher** 2024-10-28 16:26 UTC
