### ISSUE TITLE
Insert using ReadableStream

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [mariadb-corporation/mariadb-connector-nodejs#125] opened 2020-08-25 13:46 UTC
I'm inserting a large blob into  a database and I noticed that data seems to be kept in memory before being written to database. If the the data grows too large an error with code `EPIPE` is thrown. Is this how it's supposed to work? Shouldn't the data be sent to MariaDB once it's read? 

# Examples
**[Files](https://gist.github.com/natlibfi-arlehiko/8e12f446e3fbd56bc220b2c20a9d8be3)**
## Working
```sh
$ ./start-db.sh
$ DATA_LENGTH=8096000 node test.js
Starting insert
Insert done
```
## Not working
```sh
$./start-db.sh
$ DATA_LENGTH=10024000 node test.js
Starting insert
(node:11746) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:11746) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rusher** [comment] 2020-09-02 15:06
Implement design work this way when dealing with large data: 
connector will grow a temporary buffer up to 16mb, then send buffer to socket, then continue using another buffer that will be send to socket, and so on.

So normally there is no reason to have that kind of error.

I suspect that server close socket abruptly because packet size was greater that max_allowed_packet. 
could you check that with `SELECT @@max_allowed_packet ` command ?

**Comment by natlibfi-arlehiko** [comment] 2020-09-03 04:34
```sql
MariaDB [(none)]> SELECT @@max_allowed_packet
    -> ;
+----------------------+
| @@max_allowed_packet |
+----------------------+
|             16777216 |
+----------------------+
1 row in set (0.000 sec)

MariaDB [(none)]> 
```

**Comment by rusher** [comment] 2020-09-03 12:57
I did suppose that max_allowed_packet value was in 8096000 - 10024000 range.
but error would probably be more a "read ECONNRESET"  
Wrong guess then, 

I don't succeed reproducing the issue on a windows env. I will test that tonight on a Linux environment then. 
could you indicate server version (SELECT @@version) btw ?

**Comment by rusher** [comment] 2021-09-14 13:12
closing since not reproduced and no answer

**Closed by rusher** 2021-09-14 13:12 UTC
